sudo apt install cmake
sudo apt install ninja-build
sudo apt install g++
sudo apt install libx11-dev
sudo apt install libgl-dev
sudo apt install libudev-dev
sudo apt install libopenal-dev
sudo apt install vorbis-tools
sudo apt install vorbisgain
sudo apt install libsfml-audio2.5 
sudo apt install libimgui-dev 
sudo apt install libvorbis-dev
sudo apt install libflac-dev
sudo apt install libspdlog-dev
sudo apt install libboost-dev
sudo apt install libboost-all-dev
sudo apt install libdevel
sudo apt install libboost1.83-dev
sudo apt install libboost1.81-all-dev
sudo apt install libsfml-graphics2.5 
sudo apt install libgtest-dev
sudo apt install libsfml-system2.5 
sudo apt install libsfml-window2.5 
sudo apt install -y build-essential libglew-dev libglfw3-dev libglfw3 freeglut3-dev libsfml-dev
sudo apt install llvm17
sudo apt install llvm-17-dev
sudo apt install libfreetype-dev
sudo apt install libxcursor-dev
sudo apt install iwyu
sudo apt install cppcheck
sudo apt install clangd-17
